### ISSUE TITLE
TypeError: request.use is not a function

### ISSUE THREAD

**Issue by Lindenk** [koenpunt/superagent-use#5]
Running the example in the readme, I'm given the following error:

```
TypeError: request.use is not a function
    at /path/to/working_dir/node_modules/superagent-use/index.js:22:27
    at Array.forEach (native)
    at Object.superagent.(anonymous function) [as post] (/path/to/working_dir/node_modules/superagent-use/index.js:21:12)
    at repl:1:7
    at realRunInThisContextScript (vm.js:22:35)
    at sigintHandlersWrap (vm.js:98:12)
    at ContextifyScript.Script.runInThisContext (vm.js:24:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
```

I'm using version 0.1.0.

**Comment by Lindenk** [comment]
Ah, it looks like I was using an old version of superagent. Nevermind.
